version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: "wha_db"
      MYSQL_ROOT_PASSWORD: "yourdb-password"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./wha_db.sql:/docker-entrypoint-initdb.d/wha_db.sql
    networks:
      - app-network
  backend:
    build:
      context: ./wha-backend
    container_name: backend_container
    environment:
      - MYSQL_HOST=mysql_container
      - MYSQL_DATABASE=wha_db
      - MYSQL_ROOT_PASSWORD=yourdb-password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yourdb-password
    ports:
      - "6060:6060"
    depends_on:
      - db
    networks:
      - app-network
    command: ["sh", "-c", "sleep 100 && java -jar /app/app.jar"]
  frontend:
    build:
      context: ./wha-frontend-v2.0
    container_name: frontend_container
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:
networks:
  app-network:
    external: true